### ISSUE TITLE
domain expiring soon

### ISSUE THREAD

**Issue by KoryNunn** [australiasleadingjavascriptdeveloper/www#28]
Renew or na?

**Comment by MauriceButler** [comment]
tis $16 a year :money_with_wings:

**Comment by joshwnj** [comment]
still waiting for that first royalty cheque to arrive...

**Comment by joshgillies** [comment]
Thumbs up to renew, thumbs down to let it lay?

**Comment by joshwnj** [comment]
i'm `(Math.random() * 256) >> 7` on this one

**Comment by KoryNunn** [comment]
I'm 50/50, it's still kinda funny.

**Comment by SomeoneWeird** [comment]
¯\\_(ツ)_/¯

**Comment by SomeoneWeird** [comment]
@KoryNunn pls do this

**Comment by SomeoneWeird** [comment]
campjs project

**Comment by KoryNunn** [comment]
I think it's already gone.
